budget: 1000
lf_max: 0.17
lf_min: 0.147
map_ext: .png
map_path: /home/mlab/zhijunz/dreamerv2_dev/f1tenth_rl/examples/RL_example/config/maps/levine_test4
mass_max: 4.0
mass_min: 3.0
optim_method: CMA
perf_num: 6
popsize: 100
run_name: map_wide
seed: 12345
stheta: 1.37079632679
sx: 0.0
sy: 0.0
tlad_max: 5.0
tlad_min: 0.2
vgain_max: 1.5
vgain_min: 0.5
wpt_delim: ;
wpt_path: /home/mlab/zhijunz/dreamerv2_dev/f1tenth_rl/examples/RL_example/config/maps/levine_test4_wp.csv
wpt_rowskip: 3
wpt_thind: 3
wpt_vind: 5
wpt_xind: 1
wpt_yind: 2
